### PR TITLE
Covid FAQ tab

### PR DESCRIPTION
**Pull request by GauravViramgami**
Started working on covid tab. Added faq page.

### CODE REVIEW

**Comment by praveenVnktsh** [comment]
add a pic pls

**Comment by GauravViramgami** [comment]
> add a pic pls

Updated the sheet and added the image. Tried to match the resolution of the image with existing images (540 x 1140) thus the text got compressed.

**Comment by GauravViramgami** [comment]
Progress :)

covid_faqpage

**Comment by GauravViramgami** [comment]
Current Features:

- FAQs fetched from Google Sheet
- Showing it in form of Expansion Tiles
- Answer can have sub-headings

**Comment by GauravViramgami** [comment]
Structure Changed :)

covidpage

**Comment by GauravViramgami** [comment]
Added Updates Tab (Linked with Google Sheet)

covidupdates

**Pull request merged**
